services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pivma-web:local
    init: true
    ports:
      - "4025:3000"
    environment:
      API_PIVMA: ${API_PIVMA}
    restart: unless-stopped
